In [5]:
import numpy as np
from PIL import Image

def rotate_image(image_path,angle):
    img = Image.open(image_path)
    img = img.convert('RGBA')
    img_array = np.array(img)
    
    h, w, _ = img_array.shape
    print('shape',img_array.shape)
    print('ndim', img_array.ndim)
    print('size',img_array.size)
    
    print(img_array)
    
    rotated_canvas = np.zeros((h,w,4),dtype = np.uint8)
    
    center_x, center_y = w//2,h//2
    
    theta =np.radians(angle)
    
    rotation_matrix = np.array([
        [np.cos(theta), -np.sin(theta)],
        [np.sin(theta), np.cos(theta)]
    ])
    
    print('rotation matrix',rotation_matrix)
    
    for x in range(w):
        for y in range(h):
            original_coords = np.array([x - center_x, y - center_y])
            new_coords = np.dot(rotation_matrix,original_coords)
            orig_x, orig_y = new_coords + np.array([center_x,center_y])
            
            if 0<orig_x<w and 0<orig_y<h:
                rotated_canvas[y,x] =img_array[int(orig_y),int(orig_x)]
    
    rotated_image = Image.fromarray(rotated_canvas,'RGBA')
    return rotated_image




rotated_image = rotate_image('Cat_August_2010-4.jpg',45)
rotated_image.show()

            

shape (783, 1280, 4)
ndim 3
size 4008960
[[[240 240 240 255]
  [240 240 240 255]
  [239 239 239 255]
  ...
  [242 242 242 255]
  [242 242 242 255]
  [242 242 242 255]]

 [[241 241 241 255]
  [240 240 240 255]
  [240 240 240 255]
  ...
  [242 242 242 255]
  [241 241 241 255]
  [241 241 241 255]]

 [[241 241 241 255]
  [241 241 241 255]
  [240 240 240 255]
  ...
  [241 241 241 255]
  [240 240 240 255]
  [238 238 238 255]]

 ...

 [[207 207 209 255]
  [206 206 208 255]
  [210 209 214 255]
  ...
  [230 230 230 255]
  [230 230 230 255]
  [230 230 230 255]]

 [[201 201 203 255]
  [200 200 202 255]
  [205 204 209 255]
  ...
  [232 232 232 255]
  [230 230 230 255]
  [228 228 228 255]]

 [[216 216 218 255]
  [194 194 196 255]
  [211 210 215 255]
  ...
  [231 231 231 255]
  [229 229 229 255]
  [227 227 227 255]]]
rotation matrix [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]
